# Generated by Django 2.1 on 2018-08-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180822_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_date',
        ),
    ]
